version: '3.8'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ../src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: laravel-php
    volumes:
      - ../src/:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: laravel-npm    
    volumes:
      - ../src/:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    tty: true
    networks:
      - laravel